services:
  devcontainer:
    build:
      context: .
      args:
        - DEV_UID=${DEV_UID:-1000}
        - DEV_GID=${DEV_GID:-1000}
    volumes:
      - ../:/workspaces/app:cached
    command: sleep infinity
    environment:
      ROOT_DIR: /workspaces/app
      POSTMAN_API_KEY: ${POSTMAN_API_KEY}