openapi: 3.0.0
info:
  title: Akeneo PIM UI Extension
  description: Akeneo PIM UI extension endpoint manipulation
  version: 1.0.0
  contact: {}
tags: 
  - name: UI Extension 
    description: Manipulate UI Extensions
paths:
  /api/rest/v1/ui-extensions:
    get:
      summary: 'List extensions'
      description: 'List all extensions associated with your token'
      parameters: []
      operationId: list_extensions
      tags:
        - UI Extension
      responses:
        '200':
          description: |
            Returns the list of extensions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ui_extension_list_response'
    post:
      summary: 'Add an extension'
      description: |
        The `configuration` depends on the `position`. Available positions are `pim.product.tab`, `pim.category.tab` and `pim.product.header`, `pim.product-model.header`, `pim.sub-product-model.header`, `pim.product-grid.action-bar`.
        For now, the only configuration keys are the same for all the position.

        The `type` available are `iframe`, `link` and `action`. It depends on the `position` :
        - `iframe` for `pim.product.tab`, `pim.category.tab` and `pim.product-grid.action-bar`
        - `link` for `pim.product.header`, `pim.product-model.header` and `pim.sub-product-model.header`
        - `action` for `pim.product.header`, `pim.product-model.header`, `pim.sub-product-model.header` and `pim.product-grid.action-bar`
      operationId: add_extension
      tags:
        - UI Extension
      requestBody:
        description: |
          whatever
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/ui_extension_link_request"
                - $ref: "#/components/schemas/ui_extension_iframe_request"
                - $ref: "#/components/schemas/ui_extension_action_request"
      responses:
        '201':
          description: |
            Ui Extension created
          content:
            application/json:
              schema: 
                oneOf: 
                  - $ref: "#/components/schemas/ui_extension_link_response"
                  - $ref: "#/components/schemas/ui_extension_iframe_response"
                  - $ref: "#/components/schemas/ui_extension_action_response"
        '400':
          description: |
            Invalid Json
        '422':
          description: |
            Violation error
  /api/rest/v1/ui-extensions/{ui_extension_uuid}:
    patch:
      summary: 'Update an extension'
      description: |
        The `configuration` depends on the `position`. Available positions are `pim.product.tab`, `pim.category.tab` and `pim.product.header`, `pim.product-model.header`, `pim.sub-product-model.header`, `pim.product-grid.action-bar`.
        For now, the only configuration keys are the same for all the position.

        The `type` available are `iframe`, `link` and `action`. It depends on the `position` :
        - `iframe` for `pim.product.tab`, `pim.category.tab` and `pim.product-grid.action-bar`
        - `link` for `pim.product.header`, `pim.product-model.header` and `pim.sub-product-model.header`
        - `action` for `pim.product.header`, `pim.product-model.header`, `pim.sub-product-model.header` and `pim.product-grid.action-bar`
      parameters:
        - $ref: "#/components/parameters/ui_extension_uuid"
      operationId: update_extension
      tags:
        - UI Extension
      requestBody:
        description: |
          whatever
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/ui_extension_link_request"
                - $ref: "#/components/schemas/ui_extension_iframe_request"
                - $ref: "#/components/schemas/ui_extension_action_request"
      responses:
        '200':
          description: |
            Ui Extension updated
          content:
            application/json:
              schema: 
                oneOf: 
                  - $ref: "#/components/schemas/ui_extension_link_response"
                  - $ref: "#/components/schemas/ui_extension_iframe_response"
                  - $ref: "#/components/schemas/ui_extension_action_response"
        '400':
          description: |
            Invalid Json
        '422':
          description: |
            Violation error
    delete:
      summary: 'Delete an extension'
      description: 'Delete an extension'
      parameters:
        - $ref: "#/components/parameters/ui_extension_uuid"
      operationId: delete_extension
      tags:
        - UI Extension
      responses:
        '204':
          description: |
            Deleted successfully
        '404':
          description: |
            Extension does not exists
security:
  - pim_access_token: []
servers:
  - url: demo.akeneo.com
    description: ''
components:
  links: {}
  callbacks: {}
  parameters: 
    ui_extension_uuid:
      name: ui_extension_uuid
      in: path
      required: true
      schema:
        type: string
        example: e175d525-8fbf-4b26-9242-1daccf301f8b
  schemas: 
    ui_extension_list_response:
      type: array
      description: 'Represents a list of extensions'
      items: 
        anyOf: 
          - $ref: "#/components/schemas/ui_extension_link_request"
          - $ref: "#/components/schemas/ui_extension_iframe_request"
          - $ref: "#/components/schemas/ui_extension_action_request"
    ui_extension_link_request:
      type: object
      properties:
        name:
          type: string
          example: my_awesome_button_extension
        version:
          type: string
          example: V1.02.3
        description:
          type: string
          example: A short human readable description.
        position:
          type: string
          default: pim.product.header
          enum: [pim.product.header, pim.product-model.header, pim.sub-product-model.header]
        type:
          type: string
          default: link
        configuration:
          type: object
          properties:
            url:
              type: string
              example: https://www.example.com
            default_label:
              type: string
              example: My awesome link extension
            labels:
              type: object 
              properties:
                en_US:
                  type: string
                  example: My awesome link extension
                fr_FR:
                  type: string
                  example: Ma super link extension
    ui_extension_iframe_request:
      type: object
      properties:
        name:
          type: string
          example: my_awesome_iframe_extension
        version:
          type: string
          example: 20250301250
        description:
          type: string
          example: A short human readable description.
        position:
          type: string
          default: pim.product.tab
          enum: [pim.product.tab, pim.category.tab, pim.product-grid.action-bar]
        type:
          type: string
          default: iframe
        configuration:
          type: object
          properties:
            url:
              type: string
              example: https://www.example.com
            default_label:
              type: string
              example: My awesome iFrame extension
            labels:
              type: object 
              properties:
                en_US:
                  type: string
                  example: My awesome iFrame extension
                fr_FR:
                  type: string
                  example: Ma super iFrame extension
    ui_extension_action_request:
      type: object
      properties:
        name:
          type: string
          example: my_awesome_action_extension
        version:
          type: string
          example: 20250301250
        description:
          type: string
          example: A short human readable description.
        position:
          type: string
          default: pim.product.tab
          enum: [pim.product.header, pim.product-model.header, pim.sub-product-model.header, pim.product-grid.action-bar]
        type:
          type: string
          default: action
        configuration:
          type: object
          properties:
            url:
              type: string
              example: https://www.example.com
            default_label:
              type: string
              example: My awesome action extension
            labels:
              type: object 
              properties:
                en_US:
                  type: string
                  example: My awesome action extension
                fr_FR:
                  type: string
                  example: Ma super extension action
    ui_extension_link_response:
      type: object
      properties:
        uuid:
          type: string
          example: f641347d-1768-4e7b-8bb1-e2ff34b05875
        name:
          type: string
          example: my_awesome_button_extension
        version:
          type: string
          example: 2.32
        description:
          type: string
          example: A short human readable description.
        position:
          type: string
          default: pim.product.header
          enum: [pim.product.header, pim.product-model.header, pim.sub-product-model.header]
        status:
          type: string
          default: active
        type:
          type: string
          default: link
        configuration:
          type: object
          properties:
            url:
              type: string
              example: https://www.example.com
            default_label:
              type: string
              example: My awesome link extension
            labels:
              type: object 
              properties:
                en_US:
                  type: string
                  example: My awesome link extension
                fr_FR:
                  type: string
                  example: Ma super link extension
    ui_extension_iframe_response:
      type: object
      properties:
        uuid:
          type: string
          example: 5c8026f9-1617-4529-9623-1d7f8a70a89e
        name:
          type: string
          example: my_awesome_iframe_extension
        version:
          type: string
          example: 2025-03-02-109
        description:
          type: string
          example: A short human readable description.
        position:
          type: string
          default: pim.product.tab
          enum: [pim.product.tab, pim.category.tab, pim.product-grid.action-bar]
        type:
          type: string
          default: iframe
        configuration:
          type: object
          properties:
            url:
              type: string
              example: https://www.example.com
            default_label:
              type: string
              example: My awesome iFrame extension
            labels:
              type: object 
              properties:
                en_US:
                  type: string
                  example: My awesome iFrame extension
                fr_FR:
                  type: string
                  example: Ma super iFrame extension
    ui_extension_action_response:
      type: object
      properties:
        uuid:
          type: string
          example: 9c8a0eb1-64c9-4497-b09e-35300bf9aa6a
        name:
          type: string
          example: my_awesome_action_extension
        version:
          type: string
          example: 2025-03-02-109
        description:
          type: string
          example: A short human readable description.
        position:
          type: string
          default: pim.product.tab
          enum: [pim.product.header, pim.product-model.header, pim.sub-product-model.header, pim.product-grid.action-bar]
        type:
          type: string
          default: action
        configuration:
          type: object
          properties:
            url:
              type: string
              example: https://www.example.com
            default_label:
              type: string
              example: My awesome action extension
            labels:
              type: object 
              properties:
                en_US:
                  type: string
                  example: My awesome action extension
                fr_FR:
                  type: string
                  example: Ma super extension action
  securitySchemes:
    pim_access_token:
      type: apiKey
      name: access_token
      in: header